### ISSUE TITLE
Mass installer script

### ISSUE THREAD

**Issue by Daniel-dk** [openportio/openport-go#2]
Hi, I've modified a script form dataplicity which I want to include in a "standard" Rpi image which will be used on several boards, the script will register using a paid account token ( pre-populated ) so that all the boards appear on the user's account ready for remote administration/ configuration/ personalisation/ in field tweaks

I think the script sent some garbage and broke my test account.
![openport oops](https://user-images.githubusercontent.com/582384/187520892-e8a6d12b-c239-4420-832b-2594364dbdf4.png)

after some tetsing I'm also getting 
`FATAL Could not register key: ['Too many keys linked to account.']`
 - expected, but how do I remove the botched device so I  can retry with the script again ?

The script was modified from [Dataplicity](https://docs.dataplicity.com/docs/install-dataplicity-on-many-devices)

a copy of my modified Version: 
```
#!/bin/sh
# This file is /etc/network/if-up.d/mass-install-op
# modified for openport from here : https://docs.dataplicity.com/docs/install-dataplicity-on-many-devices
ACCT_TOKEN="my-test-token" # User's account token
LOG_FILE="/var/log/mass-install-op.log"

#name for these products used as part of the hostname, will be combined with Serial number
PRODUCTNAME="iotThing" 

#Wait maximum 30 seconds on network connectivity before giving up
limit=30
retry=0

#Don't bother to run when lo is configured
if [ "$IFACE" = lo ]; then
    exit 0
fi

#Only run from ifup
if [ "$MODE" != start ]; then
    exit 0
fi

if [ ! -e /opt/tunnels/mass-install-hostname ]; then
    echo "Configuring hostname..." >> $LOG_FILE 2>&1

    procinfo=$(cat /proc/cpuinfo | grep Serial)
    rpi_serial=$(echo $procinfo | tr " " "\n" | tail -c 5)
        rpi_serial="$PRODUCTNAME-$rpi_serial"

    if [ -z $rpi_serial ]; then
    echo "Raspberry Pi serial number not found" >> $LOG_FILE 2>&1
    else
    echo $rpi_serial | sudo tee /etc/hostname

    sudo sed -i '$d' /etc/hosts
    printf "127.0.0.1\t$rpi_serial\n" | sudo tee --append /etc/hosts

    sudo mkdir /opt/tunnels
    sudo touch /opt/tunnels/mass-install-hostname

    echo "Rebooting..." >> $LOG_FILE 2>&1
    sudo reboot
    fi
fi

if [ ! -e /opt/tunnels/tuxtunnel/auth ]; then
    echo $IFACE >> $LOG_FILE 2>&1

    until ping -c 1 www.google.com > /dev/null ; do
        sleep 1
        retry=$(($retry+1))
        if [ $retry -eq $limit ]; then
            echo "Interface not connected and limit reached..." >> $LOG_FILE
            exit 0
        fi
    done

    echo "Tunnels will now be created..." >> $LOG_FILE 2>&1
    openport register-key --token="$ACCT_TOKEN" --name="$rpi_serial"
    openport 1880 -d --restart-on-reboot # should this be -d ?
    openport 3000 -d --restart-on-reboot # should this be -d ? 
    openport 22 -d --restart-on-reboot  # should this be -d ? 

    #Self deletion (cleanup)
    /bin/sh -c "sudo rm /etc/network/if-up.d/mass-install-op /opt/tunnels/mass-install-hostname"
fi

```

**Comment by Daniel-dk** [comment]
I managed to remove the client and redo the test ( needed to zoom out on the page to I could get to the edit button on the -far- left )

**Comment by jandebleser** [comment]
Hi Daniel, 

Glad you found the solution to your problem. 
I see you have some comments in your script 

`    openport 1880 -d --restart-on-reboot # should this be -d ?
    openport 3000 -d --restart-on-reboot # should this be -d ? 
    openport 22 -d --restart-on-reboot  # should this be -d ? `
Yes, they should have the -d option, otherwise the script will hang.

If you have a paying account, you can also delete your keys through the API. 
You can find the full specs here:
https://openport.io/api/v2/specs/

In your case, you will need something like 
`curl -X DELETE https://openport.io/api/v2/keys/<key_id>/ -H "TOKEN: <api_token>"`
